version: 0.0
os: linux
files:
  - source: /
    # 인스턴스에서 파일이 저장될 위치
    destination: /home/ubuntu/
    overwrite: yes

permissions:
  - object: /
    pattern: "**"
    owner: ubuntu
    group: ubuntu

hooks:
  ApplicationStart:
    - location: /scripts/deploy.sh
      timeout: 60
      runas: ubuntu