# 액션이 시작할 때 기본적으로 시작하는 워크플로우
name: main

# 푸쉬하거나 풀리퀘스트 할 때 [ main ] 브랜치에서만 시작되게 함
on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

env:
  PROJECT_NAME: selldio
  S3_BUCKET_NAME: sparta7e7
  CODE_DEPLOY_APP_NAME: AWSCodeDeploy
  DEPLOYMENT_GROUP_NAME: sparta_group

# 워크블로우가 실행할 작업들 순차적으로 실행되거나, 병렬로 실행된다
jobs:
  # build라는 작업 하나만 실행하는 워크플로우
  build:
    # job을 실행하는 프로그램
    runs-on: ubuntu-20.04
    defaults:
      run:
        shell: bash
    # 실행되는 순서를 스텝에 정리
    steps:
      - uses: actions/checkout@v2

      - name: JDK 11 설치
        uses: actions/setup-java@v1
        with:
          java-version: 11

      # application.properties 생성
      - name: application.properties 생성
        # branch가 main일 때
        if: true
        run: |
          # spring의 resources 경로로 이동
          cd ./src/main/resources
          touch ./application.properties
          # GitHub-Actions에서 설정한 값을 application.properties 파일에 쓰기
          echo "${{ secrets.APPLICATION_PROPERTIES }}" > ./application.properties

      - name: ./gradlew 권한 설정
        run: chmod +x ./gradlew

      - name: Gradle 빌드
        run: ./gradlew build

      - name: zip 파일 만들기
        run: zip -qq -r ./$PROJECT_NAME.zip .

      - name: AWS 세팅
        uses: aws-actions/configure-aws-credentials@v1
        with:
          aws-access-key-id: ${{ secrets.ACCESS_KEY }}
          aws-secret-access-key: ${{ secrets.SECRET_KEY }}
          aws-region: ap-northeast-2

      - name: S3 업로드
        run: aws s3 cp --region ap-northeast-2 ./$PROJECT_NAME.zip s3://$S3_BUCKET_NAME

      - name: 코드 배치하기
        run: aws deploy create-deployment --application-name $CODE_DEPLOY_APP_NAME --deployment-config-name CodeDeployDefault.OneAtATime --deployment-group-name $DEPLOYMENT_GROUP_NAME --s3-location bucket=$S3_BUCKET_NAME,bundleType=zip,key=$PROJECT_NAME/$GITHUB_SHA.zip



